import "./globals.css"
import { ReactNode } from "react"
import Link from "next/link"

export const metadata = {
  title: "DigiCréa-Studio",
  description: "Astuces et stratégies en communication digitale",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="fr">
      <body className="bg-gray-50 text-gray-900 flex flex-col min-h-screen">

        {/* 🌐 HEADER STICKY */}
        <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-md">
          <div className="max-w-6xl mx-auto flex justify-between items-center px-6 py-4">
            <h1 className="text-2xl font-bold text-blue-900 hover:text-blue-700 transition-colors">
              DigiCréa<span className="text-orange-500">-Studio</span>
            </h1>

            <nav className="flex space-x-6 text-blue-900 font-medium">
              <Link href="/" className="relative group">
                Accueil
                <span className="absolute left-0 -bottom-1 w-0 h-0.5 bg-orange-500 group-hover:w-full transition-all duration-300"></span>
              </Link>
              <Link href="/articles" className="relative group">
                Articles
                <span className="absolute left-0 -bottom-1 w-0 h-0.5 bg-orange-500 group-hover:w-full transition-all duration-300"></span>
              </Link>
              <Link href="/about" className="relative group">
                À propos
                <span className="absolute left-0 -bottom-1 w-0 h-0.5 bg-orange-500 group-hover:w-full transition-all duration-300"></span>
              </Link>
              <Link href="/contact" className="relative group">
                Contact
                <span className="absolute left-0 -bottom-1 w-0 h-0.5 bg-orange-500 group-hover:w-full transition-all duration-300"></span>
              </Link>
            </nav>
          </div>
        </header>

        {/* 🧩 CONTENU DES PAGES */}
        <main className="flex-1 max-w-7xl mx-auto w-full p-0">
          {children}
        </main>

        {/* 🌈 FOOTER MODERNE */}
        <footer className="bg-blue-600 text-white py-6 mt-0 shadow-inner">
          <div className="max-w-6xl mx-auto text-center space-y-2">
            <p className="text-lg font-semibold">DigiCréa-Studio 💡</p>
            <p className="text-sm opacity-80">
              Astuces, tendances et stratégies en communication digitale.
            </p>
            <p className="text-sm opacity-70">
              © {new Date().getFullYear()} DigiCréa-Studio. Tous droits réservés.
            </p>
          </div>
        </footer>

      </body>
    </html>
  )
}



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
